CREATE TABLE roots_donations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES roots_users(id) ON DELETE CASCADE,
    donated_on TIMESTAMP DEFAULT now() NOT NULL,
    amount NUMERIC (8, 2) NOT NULL,
    project_name TEXT NOT NULL,
    project_description TEXT NOT NULL,
    project_url TEXT NOT NULL,
    school_name TEXT NOT NULL,
    image_url TEXT NOT NULL
);