CREATE TABLE roots_access_tokens (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES roots_users(id),
    access_token TEXT NOT NULL,
    item_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT now() NOT NULL
);