CREATE TABLE roots_roundups (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES roots_users(id),
    account_id TEXT NOT NULL,
    amount NUMERIC (8, 2) NOT NULL,
    date TEXT NOT NULL,
    name TEXT NOT NULL,
    transaction_id TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT now() NOT NULL
);